package goalsclasses;

public class FinancedGoal extends Goals {
    // Fields
    private double principleAmount;
    private double interestRate;
    private double monthlyAmount;
    private int duration;
    private boolean fixedPlan; // if the plan has been set by the user or generated by the app
    // Constructors
    public FinancedGoal(String name, double cost, double moneyDown, double interestRate, int duration) {
        super(name, cost, true);
        this.principleAmount = cost - moneyDown;
        this.interestRate = interestRate;
        this.duration = duration;
        calculateMonthly();
        fixedPlan = true;
    }
    // for plans generated by the app
    public FinancedGoal(String name, double cost) {
        super(name, cost, true);
        fixedPlan = false;
    }
    // Methods
    private void calculateMonthly() {
        monthlyAmount = (principleAmount * interestRate * (duration / 12) + principleAmount) / duration;
    }

    public void generatePlan(double interestRate, int duration, double moneyDown) throws UnsupportedOperationException {
        if (fixedPlan) {
            throw new UnsupportedOperationException("Plan is already generated");
        } else {
            // set by user class as options for the user
            this.interestRate = interestRate;
            this.duration = duration;
            this.principleAmount = this.getCost() - moneyDown;
            calculateMonthly();
        }
    }

    public int getDuration() { 
        return duration;
    }

    public double getPrinciple() {
        return principleAmount;
    }

    public double getInterestRate() {
        return interestRate;
    }

    public double getMothlyCost() {
        return monthlyAmount;
    }

    @Override 
    public String toString() {
        return "Plan for a " + this.getName() + " that cost " + this.getCost() + " with a principle of " + principleAmount + 
        " and an interest rate of " + interestRate + " over a period of " + duration + " months.\n Plan would cost " + monthlyAmount + 
        " a month.";
    }



}
